name: Deploy Flask App on Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Setup Minikube and Docker
      - name: Set up Minikube and Docker
        run: |
          # Update system and install dependencies
          sudo apt-get update
          sudo apt-get install -y curl apt-transport-https ca-certificates software-properties-common
          
          # Install Docker if not installed
          if ! command -v docker &>/dev/null; then
            echo "Docker not installed. Installing Docker..."
            sudo apt-get install -y docker.io
          fi

          # Install Minikube if not installed
          if ! command -v minikube &>/dev/null; then
            echo "Minikube not installed. Installing Minikube..."
            curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
            sudo mv minikube-linux-amd64 /usr/local/bin/minikube
            sudo chmod +x /usr/local/bin/minikube
          fi

          # Install kubectl if not installed
          if ! command -v kubectl &>/dev/null; then
            echo "kubectl not found. Installing kubectl..."
            curl -LO https://dl.k8s.io/release/v1.26.0/bin/linux/amd64/kubectl
            sudo chmod +x kubectl
            sudo mv kubectl /usr/local/bin/
          fi

      # Step 2: Start Minikube and configure kubectl
      - name: Start Minikube and update kubectl context
        run: |
          # Start Minikube and update the context for kubectl
          minikube start --driver=docker
          minikube update-context
          kubectl config use-context minikube
          echo "Minikube started and kubectl context set."

      # Step 3: Apply deployment configurations
      - name: Apply Flask Deployment YAML
        run: |
          kubectl apply -f flask-deployment.yaml --validate=false

      # Step 4: Check deployment status
      - name: Rollout status of Flask app
        run: |
          kubectl rollout status deployment flask-app || (echo "Deployment failed" && exit 1)

      # Step 5: Get all Kubernetes resources
      - name: Get all Kubernetes resources
        run: |
          kubectl get all
