name: Deploy Flask App to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Install dependencies (Minikube, Docker, kubectl)
      - name: Install Minikube, Docker, and kubectl
        run: |
          # Install Minikube
          if ! command -v minikube; then
            curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
            sudo mv minikube-linux-amd64 /usr/local/bin/minikube
            sudo chmod +x /usr/local/bin/minikube
          fi

          # Install Docker
          if ! command -v docker; then
            sudo apt-get update
            sudo apt-get install -y ca-certificates curl
            sudo apt-get install -y docker.io
            sudo systemctl start docker
          fi

          # Install kubectl
          if ! command -v kubectl; then
            curl -LO https://dl.k8s.io/release/v1.26.0/bin/linux/amd64/kubectl
            sudo mv kubectl /usr/local/bin/
            sudo chmod +x /usr/local/bin/kubectl

      # Ensure Docker is running
      - name: Ensure Docker is running
        run: |
          sudo systemctl start docker
          sudo systemctl enable docker
          sleep 15  # Wait for Docker to be ready

      # Start Minikube
      - name: Start Minikube
        run: |
          for i in {1..3}; do
            minikube start --driver=docker && break || sleep 15;
          done
          minikube status

      # Update kubectl context
      - name: Update kubectl context
        run: |
          minikube update-context
          kubectl config use-context minikube

      # Deploy Flask app to Kubernetes
      - name: Deploy Flask app to Kubernetes
        run: |
          kubectl apply -f flask-deployment.yaml --validate=false

      # Wait for the deployment to complete
      - name: Wait for deployment to complete
        run: |
          kubectl rollout status deployment flask-app-deployment --timeout=5m

      # Verify that the Flask app is running
      - name: Verify the Flask app is running
        run: |
          kubectl get pods

      # Expose the Flask service
      - name: Expose Flask service in Minikube
        run: |
          kubectl expose deployment flask-app-deployment --type=NodePort --name=flask-app-service
          kubectl get svc flask-app-service

      # Get Minikube IP and Flask app URL
      - name: Get Minikube IP and Flask app URL
        run: |
          minikube_ip=$(minikube ip)
          minikube_service_port=$(kubectl get svc flask-app-service -o=jsonpath='{.spec.ports[0].nodePort}')
          echo "Flask app is available at http://$minikube_ip:$minikube_service_port"
          echo "FLASK_APP_URL=http://$minikube_ip:$minikube_service_port" >> $GITHUB_ENV

      # Optionally, print out the Flask app URL for use later
      - name: Print Flask app URL
        run: |
          echo "Flask app URL: ${{ env.FLASK_APP_URL }}"
