name: Deploy Flask App with Public Image on Minikube

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: public-dockerhub-image/flask-app:latest
  KUBECONFIG: /home/runner/.kube/config

jobs:
  deploy:
    name: Deploy to Kubernetes Cluster on Self-Hosted Minikube
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Start Minikube (if not running)
        run: |
          minikube status || minikube start --driver=docker

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure Kubeconfig for Minikube
        run: |
          mkdir -p ~/.kube
          minikube kubeconfig > ~/.kube/config

      - name: Deploy App to Kubernetes
        run: |
          kubectl apply -f flask-deployment.yaml

      - name: Verify Deployment
        run: |
          kubectl rollout status deployment flask-app || (echo "Deployment failed" && exit 1)

  notify:
    name: Notify on Failure
    needs: deploy
    runs-on: self-hosted
    if: failure()

    steps:
      - name: Print Error Log
        run: echo "Deployment to Kubernetes failed. Check the logs for more details."

      - name: Notify Slack (Optional)
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "channel": "#your-channel",
              "text": "Deployment failed. Check GitHub Actions logs."
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
